### ISSUE TITLE
Unable to add Governance framework on new fresh install

### ISSUE THREAD

**Issue by thnilsen** [simplerisk/code#10]
This is a new fresh install of SimpleRisk 20180104-001 on a Centos 7 install.

The Governance -> Frameworks list is emply. When trying to registering a new framework the following errors are generated.

PHP Notice:  Undefined index: parent in /var/www/html/simplerisk/governance/index.php on line 69, referer: https://simplerisk.example.local/governance/index.php
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'parent' cannot be null' in /var/www/html/simplerisk/includes/governance.php:601\nStack trace:\n#0 /var/www/html/simplerisk/includes/governance.php(601): PDOStatement->execute()\n#1 /var/www/html/simplerisk/governance/index.php(81): add_framework('GDPR', '', NULL)\n#2 {main}\n  thrown in /var/www/html/simplerisk/includes/governance.php on line 601, referer: https://simplerisk.example.local/governance/index.php

Since no existing framework is available, the parent will be null by default. However, the DB schema does not allow NULL

```
MariaDB [simplerisk]> explain frameworks;
+-------------------+---------+------+-----+---------+----------------+
| Field             | Type    | Null | Key | Default | Extra          |
+-------------------+---------+------+-----+---------+----------------+
| value             | int(11) | NO   | PRI | NULL    | auto_increment |
| parent            | int(11) | NO   |     | NULL    |                |
| name              | blob    | NO   |     | NULL    |                |
| description       | blob    | NO   |     | NULL    |                |
| status            | int(11) | NO   |     | 1       |                |
| order             | int(11) | NO   |     | NULL    |                |
| last_audit_date   | date    | YES  |     | NULL    |                |
| next_audit_date   | date    | YES  |     | NULL    |                |
| desired_frequency | int(11) | YES  |     | NULL    |                |
+-------------------+---------+------+-----+---------+----------------+

```

**Comment by jsokol** [comment]
Hello, thanks for reporting your issue.  It sounds like you've installed SimpleRisk on a MySQL instance with STRICT SQL MODE enabled.  Here is a link to a support article that describes how to disable it:

https://simplerisk.freshdesk.com/solution/articles/6000045597-why-do-i-see-a-fatal-error-noting-that-a-database-field-doesn-t-have-a-default-value-

Once doing this, this functionality should work just fine.
