### ISSUE TITLE
'Risk "{$subject}" has been submitted successfully.' shows &quot;

### ISSUE THREAD

**Issue by milovanderlinden** [simplerisk/code#16]
When you submit a risk, the message shows: 

`Risk &quot;myrisk&quot; has been submitted successfully.`

It seems that the `protected $htmlSpecialCharsFlags = ENT_QUOTES;` in `Escaper.php` causes this. Perhaps this variable needs to be `ENT_NOQUOTES`

**Comment by jsokol** [comment]
Yes, this was a bug in the last release of SimpleRisk and has been fixed in our development branch.  It will roll live with the Q4 2018 release of SimpleRisk.
