### ISSUE TITLE
Update Dutch NL translation

### ISSUE THREAD

**Issue by milovanderlinden** [simplerisk/code#17]
I want to update the dutch translation. Currently it is a bit strange, has it been machine translated? I will go and fix this and send a pull request.

**Comment by jsokol** [comment]
Hello!  We'd love for you to help with the Dutch translation.  Sadly, yes, it was done with machine translation.  That said, the best way todo this is to use our Crowdin page to make the updates:

https://crowdin.com/project/simplerisk/nl#

Please let us know if you run into any issues.

**Comment by milovanderlinden** [comment]
Thanks, I will reach out on crowdin. I also discovered untranslated strings which I am migrating in to all translations. I am adding them using the original english string, is that ok? Would you like to receive a pull request for them when I am finished?

**Comment by jsokol** [comment]
Yeah, untranslated strings (ie. those not in the language file) we probably need to do a pull request on.  Thank you!
