### ISSUE TITLE
Getting Blank Screen when adding Role to user "admin/role_management.php"

### ISSUE THREAD

**Issue by GaneshKandu** [simplerisk/code#21]
Hi,

I am getting blank screen when adding Role to user in SimpleRisk 20190630-001

**Steps to Reproduce**

Configure > role_management > Add a New Role
add some user
Configure > role_management > Role
select "User" check some "User Responsibilities" and save

**Error**

``
Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'simplerisk.USER' doesn't exist' in includes/functions.php:12013
``

``
Array
(
    [type] => 1
    [message] => Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'simplerisk.USER' doesn't exist' in includes/functions.php:12013
Stack trace:
#0 includes/functions.php(12013): PDOStatement->execute()
#1 admin/role_management.php(70): save_role_responsibilities(3, Array)
#2 {main}
  thrown
    [file] => includes/functions.php
    [line] => 12013
)
``

This may be because [Identifier Case Sensitivity](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html)

**Comment by jsokol** [comment]
Can you please try going to line 12013 in the includes/functions.php table and changing the line reading:

$sql = "UPDATE `USER` SET ";

to

$sql = "UPDATE `user` SET ";

We haven't run into this before, but that should fix it if your hypothesis on the Identifier Case Sensitivity is correct.

**Comment by GaneshKandu** [comment]
Hi @jsokol 

Changing table name to lowercase Works for me

Changed lines are 11956, 12002, 12018
```php
$sql = "UPDATE user SET ";
```

**Comment by jsokol** [comment]
OK, cool.  We've already fixed this in our dev code which will go live with the next release.  I'll leave this issue open until that rolls live.  Thank you for reporting!

**Comment by GaneshKandu** [comment]
> which will go live with the next release

Any update ?

**Comment by jsokol** [comment]
The next release is intended to go live before the end of September.

**Comment by jsokol** [comment]
The SimpleRisk 20190930-001 release is now live.
