### ISSUE TITLE
Affected Assets in Submit Risk does not show the assets

### ISSUE THREAD

**Issue by mazawi** [simplerisk/code#22]
Hi ,,
I have installed SimpleRisk on local server but when I submit a risk the affected assets box does not show the previous assets and instead it shows only Add (...). 
I have confirmed the assets and added new assets from assets management but still the problem was not solved.
I have install it to different servers or computers and different versions of Xampp but still the problem is not solved.
more info:
I am using Windows 10 and Xampp 5.6.36 as recommended 

many thanks

**Comment by jsokol** [comment]
Hello.  This does not sound like an issue that we've experienced before.  That said, I'm pretty sure that XAMPP 5.6.36 runs PHP 5.6.36 by default, which is no longer supported.  SimpleRisk has been updated to only support PHP 7.x going forward.  This is likely why you are experiencing issues.  If you update to use PHP 7.x and are still experiencing an issue, we would recommend submitting a ticket to support AT simplerisk DOT com.  Thanks!
