### ISSUE TITLE
Update Application Files in Docker Image

### ISSUE THREAD

**Issue by gveltri** [simplerisk/code#26]
Hey SimpleRisk team!

My docker deployment of SR seems to be broken because of a line in the ping_server function in the functions.php file.

line 11588 of functions.php
```
require_once(realpath(__DIR__ . '/../extras/upgrade/index.php'));
```

This line has been commented out in the main code repository but still exists on the simplerisk docker image. I checked the image, and there's no ../extras/upgrade/index.php. Currently, it's throwing a 500 error when a user tries to login.

thanks,
Gerardo

**Comment by jsokol** [comment]
Gerardo,

I've tested the DockerHub image and it has that line commented out.  The Dockerfile install method downloads the latest code, which should also have that commented out.  The one big discrepancy that I'm seeing is that the latest code has this on line 11313, but you said line 11588.  I'm thinking that perhaps you aren't running the latest code base.  Did you try to upgrade SimpleRisk?  What version were you upgrading from?  

It also sounds like maybe you registered your SimpleRisk instance, which would enable the registration_registered setting value, but the Upgrade Extra that it downloads has been removed somehow.  My recommendation on the easiest way to get you back up and running properly would be to follow the instructions here to disable the registration:

https://simplerisk.freshdesk.com/a/solutions/articles/6000217414

Once you do that, then you can re-register and it should work.

**Comment by gveltri** [comment]
Thanks so much! I tried rebuilding the image, but I was still getting the old code base. Perhaps the older version was cached.

**Comment by jsokol** [comment]
Does that mean the issue has been resolved now?

**Comment by gveltri** [comment]
The guide you linked solved our 500 error! I'll try updating the image as well, but yes, issue resolved.
