### ISSUE TITLE
Error with gui installer

### ISSUE THREAD

**Issue by stboissdev** [simplerisk/code#30]
Hello,

when i start gui installer , I have the following error after add my admin user:
 simplerisk_1  | [26-Apr-2022 14:37:29 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'PRIMARY' in /var/www/simplerisk/includes/install.php:1831

**Comment by DASimp** [comment]
Thank you for reaching out. We have updated the installation instructions to include the use of a new installation method which will remove this roadblock. You will find the updated instructions in the same place as the original. The condensed version of what you will need to do is first remove the database that was half created by following the steps found here: https://simplerisk.freshdesk.com/a/solutions/articles/6000169889

Now you can attempt to install again by simply hitting the url localhost or where ever you setup your installation to be accessible please note that the key difference here is there is no need to append the /install to the URL.  This should allow you to use the new installer which will not run into the same issue. If you have continued problems please let us know and we are happy to help and you have my sincere apologies for the disruption.

**Comment by jsokol** [comment]
As this should be resolved by using the new installer, I am marking this issue as closed.  Feel free to reach out to SimpleRisk Support if it doesn't work as expected.

**Comment by stboissdev** [comment]
Hi,

I still have the issue.

i am on docker with last version

on install database, the script insert  data in table user_to_team even if user doesn't exist. [https://github.com/simplerisk/database/blob/933454629660a63bfc7314f00a2abd7df519ecb8/simplerisk-en-20220401-001.sql#L3033](https://github.com/simplerisk/database/blob/933454629660a63bfc7314f00a2abd7df519ecb8/simplerisk-en-20220401-001.sql#L3033)
with gui installer, the first user are create and also link to team with same id already created

**Comment by stboissdev** [comment]
@jsokol,
can you reopen this issue, please.

**Comment by jsokol** [comment]
Hello @stboissdev.  It is unclear what you are trying to do here.  If you are using a Docker version of SimpleRisk, you will not use the GUI installer, as the Docker image automatically installs the SimpleRisk database for you.  These two methods are not compatible.  The instructions for running a SimpleRisk Docker can be found [here](https://www.simplerisk.com/download/docker).  If you were trying to upgrade an existing instance, then you would follow the upgrade guide [here](https://simplerisk.freshdesk.com/support/solutions/articles/6000045609-simplerisk-upgrade-guide).
