### ISSUE TITLE
APIs documentation 

### ISSUE THREAD

**Issue by crfrancesco** [simplerisk/code#37]
hi, I would like to use the open source version of simple risk for an R&D project. is it possible to share the documentation of the APIs exposed by the platform? Thank you.

**Comment by jsokol** [comment]
Hey there!  Our free and open source "SimpleRisk Core" has the ability to push and pull data from the API endpoints, but only using the cookie-based authentication.  If you require the ability to provision API keys for programmatic interaction, you would likely need our API Extra.  Regardless, documentation around the API can be found [here](https://simplerisk.freshdesk.com/support/solutions/folders/6000227922).
