### ISSUE TITLE
SECURE CONTROLS FRAMEWORK (SCF) EXTRA

### ISSUE THREAD

**Issue by crfrancesco** [simplerisk/code#38]
hi, as I read on your site, SCF is a free extra correct ? I installed the free version, using the docker container, but the integration with the SCF is not available inside. Where am I doing wrong ? do i need to install a plugin? thanks to the availability.

**Comment by jsokol** [comment]
Hello.  The SCF is a free Extra, but requires registration of your SimpleRisk instance.  Go to Configure -> Register & Upgrade and enter your registration information.  Once you do that, you should see the option to download and install the SCF Extra.

**Comment by crfrancesco** [comment]
thanks for your prompt reply

**Comment by crfrancesco** [comment]
i'm trying to register my local simplerisk instance but the request keeps loading without terminating. what are the requirements to allow a correct registration? I received the confirmation email correctly. i checked and all health checks are ok. could you help me ? Thank you
