### ISSUE TITLE
app login keeps loading for a long time

### ISSUE THREAD

**Issue by crfrancesco** [simplerisk/code#39]
Hi, I installed the free version in the docker container for an R&D project. subsequent logins take a very long time. Do you have any idea what the problem could be? also for some features of the platform the loading times in chrome or edge are very long. Thank you

**Comment by jsokol** [comment]
Hello,

It sounds like your container is having issues reaching the Internet.  Most of the time, these performance issues are related to resources that the page requires timing out.  Do you have an outbound firewall or some sort of a proxy?  That would be my first guess.

On another note, I'd like to request that you stop submitting Issues in GitHub for each of these problems you are experiencing.  We have a dedicated Support Team and a system for managing those.  When used, they ensure that you get the most prompt support responses possible.  With GitHub, it's only me or Pedro who will be able to respond to you.  You can find that system [here](https://support.simplerisk.com) or by emailing support [AT] simplerisk.com.  Thanks.
