### ISSUE TITLE
simplerisk compatability with Azure Database for MySQL flexible server?

### ISSUE THREAD

**Issue by CharlesGillanders** [simplerisk/code#42]
I am trying to deploy simplerisk 20231103, I successfully deployed it in a test virtual machine using the full local install including a MySQL server.

I dumped the resulting database, imported it into an existing Azure Database for MySQL flexible server, created a matching mysql user with the same permissions on the new database and tested from the VM that I could connect and see the database and tables using the mysql command line with the cloned user.

I edited the /var/www/simplerisk/includes.config.php file to change the value of DB_HOSTNAME to use my Azure DB server, restarted apache2 and I am instantly getting a message that simplerisk is "Unable to Communicate with the Database".

There are no database error messages in the Apache logs that I can see - is there some way to increase the verbosity so that I can find out more about this error?

**Comment by jsokol** [comment]
@CharlesGillanders This is not a code issue so I am closing this.  Please send your inquiry in to our support email.  Thank you.
