### ISSUE TITLE
Improvements to System Menus and Texts for the Brazilian Portuguese version

### ISSUE THREAD

**Issue by EliMCosta** [simplerisk/code#45]
Improve the translation into Brazilian Portuguese, which is far below the fenomenal quality of the system.
The changes have to be applied to values on [lang.bp.php](https://github.com/simplerisk/code/blob/master/simplerisk/languages/bp/lang.bp.php) file.

**Comment by EliMCosta** [comment]
Can I open a PR in order to solve this issue?

**Comment by jsokol** [comment]
Hello Eli.  Thanks for reaching out about the issues with the Brazilian Portuguese translations.  As you can imagine, we do our best to support many of these languages, even though we don't speak them using machine translation.  We would welcome the opportunity to work with you to improve our translations, however, committing a new lang.bp.php file is not the appropriate path.  We leverage a program called Crowdin to manage our language translations and you can contribute there.  Simply go [here](https://translate.simplerisk.com/project/simplerisk/pt-BR) to create an account and propose your translations.  Once accepted, they will automatically be integrated into our next release.  Feel free to reach out to support@simplerisk.com with any questions.
