### ISSUE TITLE
.../includes/api.php:4688 error after upgrading to "20240726-001"

### ISSUE THREAD

**Issue by vh-arctia** [simplerisk/code#47]
Hello,

SimpleRisk docker container fails with the following error when attempting to edit a framework after upgrading to "20240726-001":

> [Sat Aug 17 18:45:48.676048 2024] [php:notice] [pid 332] [client 172.16.0.11:60812] Leaf\\Exceptions\\ErrorException thrown with message "foreach() argument must be of type array|object, null given"\n\nStacktrace:\n#7 Leaf\\Exceptions\\ErrorException in /var/www/simplerisk/includes/api.php:4688\n#6 Leaf\\Exception\\Run:handleError in /var/www/simplerisk/includes/api.php:4688\n#5 getFrameworkResponse in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:531\n#4 call_user_func_array in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:531\n#3 Leaf\\Router\\Core:invoke in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:521\n#2 Leaf\\Router\\Core:handle in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:466\n#1 Leaf\\Router\\Core:run in /var/www/simplerisk/vendor/leafs/leaf/src/App.php:382\n#0 Leaf\\App:run in /var/www/simplerisk/api/index.php:569\n, referer: https://xxx:1447/governance/index.php

Version "20240603-001" works fine. 

Installation is following the "Compiled docker image" instructions listed [here](https://www.simplerisk.com/download/docker).

Steps to reproduce:

1. Install docker container.
2. Upgrade to "20240726-001"
3. Add a control framework.
4. Click edit for the control framework.

**Comment by jsokol** [comment]
@vh-arctia I have replicated this issue in a Docker environment.  The odd thing is that we run these same Docker images for our customers and they are not experiencing the same issue.  We will investigate and provide an update once one is available.

**Comment by vh-arctia** [comment]
Thanks. I assume those customers have Customization extra.

**Comment by jsokol** [comment]
We have verified the issue and have a fix developed.  We are working on a new release version as I write this.  I hope to have it live before the end of the day today.

**Comment by vh-arctia** [comment]
This has been fixed by 20240818-001.
