### ISSUE TITLE
error in .../simplerisk/includes/api.php:4636 when customization extra is not in use

### ISSUE THREAD

**Issue by vh-arctia** [simplerisk/code#48]
Almost identical to #47 except this time the following error gets thrown when attempting to edit a control in Governance => Define Control Frameworks => Controls:

> [Sun Aug 18 20:55:23.650579 2024] [php:notice] [pid 27103] [client 172.17.0.1:44670] Leaf\\Exceptions\\ErrorException thrown with message "foreach() argument must be of type array|object, null given"
> 
> Stacktrace:
> `#7` Leaf\\Exceptions\\ErrorException in /var/www/simplerisk/includes/api.php:4636
> `#6` Leaf\\Exception\\Run:handleError in /var/www/simplerisk/includes/api.php:4636
> `#5` getControlResponse in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:531
> `#4` call_user_func_array in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:531
> `#3` Leaf\\Router\\Core:invoke in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:521
> `#2` Leaf\\Router\\Core:handle in /var/www/simplerisk/vendor/leafs/router/src/Router/Core.php:466
> `#1` Leaf\\Router\\Core:run in /var/www/simplerisk/vendor/leafs/leaf/src/App.php:382
> `#0` Leaf\\App:run in /var/www/simplerisk/api/index.php:569
> , referer: https://xxxx/governance/index.php

This also occurs with latest version "20240818-001"

**Comment by jsokol** [comment]
Thanks for this!  I'll get the dev team on it ASAP.  We will hopefully have a fix for it tomorrow.

**Comment by jsokol** [comment]
@vh-arctia A new 20240819-001 release has now been deployed which fixes this and one similar issue, as well.  Please let us know if you have any questions or additional issues.
