### ISSUE TITLE
reset_password.php references unavailable css

### ISSUE THREAD

**Issue by mmickelson** [simplerisk/code#49]
After installing Simple Risk core, I found that the reset password screen was taken over by the Simple Risk logo. Shrinking the width of the page make the form usable.
<img width="753" alt="clipboard-202409101843-6za12" src="https://github.com/user-attachments/assets/833b015c-1138-4f9c-abf7-7d1a43a73b42">

After investigating, it seems that the css files were 404.

**Comment by jsokol** [comment]
@mmickelson Thanks for letting us know.  Can you please let us know what version of SimpleRisk you are running and what installation method was used?  We have a new release ready to launch on Friday and I don't see this issue there.  It's also a bit perplexing as these CSS files you are referencing shouldn't even be under that "css" directory any longer.  I'm guessing this is something we found and fixed for this new release.

**Comment by mmickelson** [comment]
The version is 20240819-001. I'm asking IT which specific method they used to install it.

**Comment by jsokol** [comment]
Did you recently upgrade to this version?  Best I can tell, this is not an issue with that release of SimpleRisk as I am unable to replicate on an instance running the same version.  If I had to guess, it sounds like maybe your browser cached that page and is trying to load CSS that no longer is relevant.  Try hitting it in Incognito Mode or in another browser to see if you continue to get the same resultts.

**Comment by mmickelson** [comment]
It's a fresh install completed yesterday. We haven't used the software before, I just learned about it last week and asked for an instance to install it on. I provided the link to the download page to IT so I am sure it was freshly downloaded.

**Comment by mmickelson** [comment]
IT used the docker-compose version found here: https://github.com/simplerisk/docker/blob/master/stack.yml

**Comment by jsokol** [comment]
OK, that's helpful.  I think I may see where the issue lies.  Let me feed this off to our development team to have a look at it.

**Comment by jsokol** [comment]
I believe this issue has been resolved so I am going to close this out, but if you have any questions or problems, please don't hesitate to reach out.
