### ISSUE TITLE
Issues during update with Custom Auth Extra

### ISSUE THREAD

**Issue by kale1d0code** [simplerisk/code#50]
Hi All,

I'm building my own implementation of SSO for simplerisk.
I noticed there is some components in simplerisk already to get this to work.
(links to sso login on login screen controlled by database value)

When updating simplerisk, I kept running into issues as simplerisk was trying to update my code.
is there a way to build a custom implementation of an extra without causing problems with the update process?

**Comment by jsokol** [comment]
Hello @kale1d0code.  No, we wouldn't support you writing your own version of our Extras.  Our Extras are priced considerably less than any other product on the market.  Our Starter Package includes 3 Extras and Support for $5k USD.  Our recommendation would be to purchase the Custom Authentication Extra if you require SAML/SSO integration with SimpleRisk.
